# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-09-24 13:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_title', models.CharField(max_length=32)),
                ('b_content', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='BlogUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_username', models.CharField(max_length=32)),
                ('b_password', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='b_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.BlogUser'),
        ),
    ]
